services:
  db:
    image: postgres:latest
    container_name: book.db
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=test
      - POSTGRES_PASSWORD=test
      - POSTGRES_DB=test
    volumes:
      - ./volumes/postgres_data:/var/lib/postgresql/data

  web:
    build: 
      context: ./source/ 
    container_name: book.web
    ports:
      - "8000:8000" 
    depends_on:
      - db
    restart:
      always

  proxy:
    image: nginx:1.27-alpine
    container_name: book.proxy
    volumes:
      - ./volumes/static/:/static/
      - ./volumes/nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:  
      - "80:80"
    depends_on:
      - web
