# Generated by Django 5.1.2 on 2024-11-30 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="address",
            field=models.CharField(null=True),
        ),
    ]
