# Generated by Django 5.1.2 on 2024-11-30 14:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0002_user_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(default=""),
        ),
    ]
