# Generated by Django 5.1.2 on 2024-12-01 11:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("login", "0003_alter_user_address"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "Пользователя",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
